"""empty message

Revision ID: 885651db7e82
Revises: 26551645aee8
Create Date: 2019-03-02 14:32:02.513484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885651db7e82'
down_revision = '26551645aee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('reset_password_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'reset_password_token')
    # ### end Alembic commands ###
